// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDAj93qG8r356KCZzLEHb7zvGZGCAl6Lw',
    appId: '1:990830593632:web:b390cb3cd346d9d225a505',
    messagingSenderId: '990830593632',
    projectId: 'mygym-c0ad1',
    authDomain: 'mygym-c0ad1.firebaseapp.com',
    storageBucket: 'mygym-c0ad1.firebasestorage.app',
    measurementId: 'G-44412KLCWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBythAZ3aeHt0oyZtmv-iaCO-GpHg0QU80',
    appId: '1:990830593632:android:c34ba5c778ab5e1a25a505',
    messagingSenderId: '990830593632',
    projectId: 'mygym-c0ad1',
    storageBucket: 'mygym-c0ad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIejFHfTVqcfzi2TioUNbF_ZG1Jx-WmBs',
    appId: '1:990830593632:ios:da45604399dbddaf25a505',
    messagingSenderId: '990830593632',
    projectId: 'mygym-c0ad1',
    storageBucket: 'mygym-c0ad1.firebasestorage.app',
    iosBundleId: 'com.example.mygym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIejFHfTVqcfzi2TioUNbF_ZG1Jx-WmBs',
    appId: '1:990830593632:ios:da45604399dbddaf25a505',
    messagingSenderId: '990830593632',
    projectId: 'mygym-c0ad1',
    storageBucket: 'mygym-c0ad1.firebasestorage.app',
    iosBundleId: 'com.example.mygym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDAj93qG8r356KCZzLEHb7zvGZGCAl6Lw',
    appId: '1:990830593632:web:2fab24c1edb6405925a505',
    messagingSenderId: '990830593632',
    projectId: 'mygym-c0ad1',
    authDomain: 'mygym-c0ad1.firebaseapp.com',
    storageBucket: 'mygym-c0ad1.firebasestorage.app',
    measurementId: 'G-PK3DV1KC3Q',
  );
}
